version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=your-api-key
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

